name: HoloTools
version: '${version}'
main: net.kokoricraft.holotools.HoloTools
api-version: '1.19'
commands:
  holotools:
    usage: /<command> help
    permission: holotools.help

permissions:
  holotools.help:
    description: Permission to use main command
    default: op
  holotools.command.give:
    description: Give players permission to give a tool
    default: op
    children:
      holotools.help: true
  holotools.command.reload:
    description: Give players permission to reload the plugin
    default: op
    children:
      holotools.help: true